export default {
    MovingAndStorage: [

        'Local moving in Dubai',
        'Moving from Villa to villa',
        'Moving from Villa to apartment',
        'Moving from apartment to villa',
        'Moving from apartment to apartment',
        'Moving within Marina',
        'Moving within JLT',
        'Moving within JBR',
        'Moving within Springs',
        'Moving within Arabean Ranches',
        'Moving within Damac hills',
        'Moving within Barsha',
        'Moving within Jumeirah Park',
        'Moving within Jumeirah Island',
        'Moving within Dubailand',
        'Moving within Dubai hills',
        'Moving within Tecom',
        'Moving within Shaikh zayed road',
        'Moving within Businessbay',
        'Moving within Oldtown',
        'Moving within Jumeirah village trainagle',
        'Moving within Jumeirah village circle',
        'Moving from Dubai to Abudhabi',
        'Moving From Dubai to Sharjah'],

    PackingAndMovingService: [
        'Packing for furnitures',
        'Boxes for Cloths',
        'Boxes for Books',
        'Boxes for Shoes',
        'Boxes for cutlery & Utensils',
        'Boxes for toys',
        'Hanging boxes for unfoldable cloths',
        'Flat boxes for long dress',
        'Jumbo Boxes for weightless cloths',
        'Bubble for mirrors',
        'Bubble or glass items',
        'Corrugated sheets for Chest of drawer',
        'Corrugated sheet for Wardrobes',
        'Corrugated sheet for sofa',
        'Wrapping paper for Kitchen stuff',
        'Closed Trucks for moving',
    ],

    OfficeMovingInDubai:
        ['Full office move within Dubai',
            'Partial Office move within Dubai',
            'Office tables move within Dubai',
            'Full office move within Abudhabi',
            'Partial Office move within Abudhabi',
            'Office tables move within Abudhabi',
            'Furniture moving in Dubai'],

    InternationalMovingFromDubai:
        ['Moving to Qatar from Dubai',
            'Moving to Oman from Dubai',
            'Moving to Saudi from Dubai',
            'Moving to Phillipines from Dubai',
            'Moving to Australia from Dubai',
            'Moving to Canada from Dubai',
            'Moving to India from Dubai',
            'Moving to the UK from Dubai',
            'Moving to the USA from Dubai',
            'Groupage Moving service to Qatar',
            'Groupage Moving service to Oman',
            'Groupage Moving service to Saudi',
            'Groupage Moving service to Philippines',
            'Groupage Moving service to Australia',
            'Groupage Moving service to Canada',
            'Groupage Moving service to India',
            'Groupage Moving service to UK',
            'Groupage Moving service to USA'],

    StorageInDubai: [
        'Furniture Storage in Dubai',
        'Self Storage in Dubai',
        'House hold storage in Dubai',
        '24/7 Access storage ',
        'Climate control storage',
        'AC self storage',
        'Storage rooms for commercial',
        'Storage rooms for personal effects',
        'storage solutions'
    ],
    OtherServices: [
        'Car shipping in Dubai',
        'Maintenance & Handyman',
        'Handyman in Dubai',
        'Home Maintenance in Dubai',
        'Curtain and blinds hanging in Dubai',
        'Curtains and blinds in Dubai',
        'Electrician in Dubai',
        'Furniture assembly in Dubai',
        'Home Appliance Repair and Installation in Dubai',
        'TV Mounting in Dubai',
        'Painting',
        'Painting in Dubai']
}